### ISSUE TITLE
为什么不用go，java已经被淘汰了

### ISSUE THREAD

**Issue by SteveCruise** [hl845740757/fastjgame#1]

**Comment by SteveCruise** [comment]
回调也不能用，应该用协程

**Comment by hl845740757** [comment]
回调可以用啊？  
1.  对于go，我目前仅仅是观望态度，并没有进行学习。 学习语言吧，入门还是容易的，但是要足够深入才有意义。
2.  go有它的优势，但java还不至于被淘汰。
3.  对于技术不能盲从的，协程固然有它的优势，但是就没有缺陷吗？ eg: 保存堆栈更容易内存泄漏。此外它也并没有真正解决异步，代码看似是同步的，但紧挨着的两行代码的执行环境却可能是不一样的。

**Comment by hl845740757** [comment]
> 回调也不能用，应该用协程
回调可以用啊？  
1.  对于go，我目前仅仅是观望态度，并没有进行学习。 学习语言吧，入门还是容易的，但是要足够深入才有意义。
2.  go有它的优势，但java还不至于被淘汰。
3.  对于技术不能盲从的，协程固然有它的优势，但是就没有缺陷吗？ eg: 保存堆栈更容易内存泄漏。此外它也并没有真正解决异步，代码看似是同步的，但紧挨着的两行代码的执行环境却可能是不一样的。

**Comment by SteveCruise** [comment]
行吧，我都用过，你这选型开发效率太低
